language: c
sudo: required
dist: focal

before_script:
  #installing libsodium, needed for Core
  - git clone git://github.com/jedisct1/libsodium.git > /dev/null
  - cd libsodium
  - git checkout tags/1.0.15 > /dev/null
  - ./autogen.sh > /dev/null
  - ./configure > /dev/null
  - make check -j3 > /dev/null
  - sudo make install >/dev/null
  - cd ..

  #installing yasm, needed for compiling vpx
  - sudo apt-get install yasm > /dev/null
  #creating libraries links and updating cache
  - sudo ldconfig > /dev/null
  #installing check, needed for unit tests
  - sudo apt-get install check cmake cscope python3-requests python3-jinja2 cscope libevent-dev libevent-pthreads-2.1
  - cd ..
    # toxcore
  - git clone https://github.com/TokTok/c-toxcore.git
  - cd c-toxcore
  - cmake . -DBUILD_TOXAV=OFF
  - make -j3
  - sudo make install
  - sudo ldconfig
  - cd ..
  - pushd .

script:
  - popd
  - cd tuntox
  - find .. -name Makefile
  - make tuntox_nostatic

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VjQmHxt7StKi1XF45IaYei3/0GtpIjeCeySLCPyHYnSlTMYw1VWti9Pow2Vr7mses27KddWhgl54hYjukaqyNFklfz+cXuke+VSwLp/wKlC7hV+frsrodWCd35hvNDZV3Q49e1u0944Oz4ggiS1yX1+dlXZO/v6HINXouSJbbk/0UowW4T6vkD5x/Muq7ddf5J9qMr6XF7oGzZO/fHnWO4B+xILiWs3R6gk24B8IksHiHEDIsruGnbSx2OUvoYiyNOW9hVczf2DIMZVKhqWxCX7/dEs2E5K4+/pbGfww4JhbGUMtkkGk97a7Y8rdXhs1l+k5IbG9MoZ5MxcyE1t8DRJSiT8SI50AUzDZGpU7YKIRWFxj9hyIlxPuv9aL3AyhGDzHCLAUGCtV0LYWuXUKusfQ3YuWoc/Z+6I9tIDBUdGtPp8R+P7x2pHnq08PQecBgGh+KOj2rkJBv3jP5GTrH7OtjwdKQyggni+otL/0ydq9Cj67sbt2jerjlBWtI4Vg2jVbRwIT2jDcUCMwrL5kCkuXiSvywlvA/qLVIkAvLILdbIXFBUYh/N4z00YiiVhpbc3AkJaiuhDtese272nXPeYTw6qtQnZyoud3jQjWpGmsD7uYstbnRNYsmYWf4Nz2+XIJtAmqHBhRYuq50Q1ImPY2cJyo0yZ6tniSKCcqHRI="

addons:
  coverity_scan:
    project:
      name: "gjedeer/tuntox"
      description: "Build submitted via Travis CI"
    notification_email: gdr@gdr.name
    build_command_prepend: "cd tuntox; make clean"
    build_command:   "make"
    branch_pattern: master

